config/routes.rb
Rails.application.routes.draw do
  resources :wikis

  devise_for :users

  get 'about' => 'welcome#about'
  
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.all
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocpedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Blocpedia", root_path %></li>
    <li><%= link_to "About", about_path %></li>

    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
      - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
    <% else %>

      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
    <% end %>
  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wiki</p>
    <ul>
      <li>One</li>
      <li>Two</li>
      <li>Three</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div class="row">
  <div class="col-md-4">
    <p>
      Guidelines:
    </p>
    <ul>
      <li>One</li>
      <li>Two</li>
      <li>Three</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', placeholder: "Enter post body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save" , class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>

</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @wiki.body %></p>
  </div>
  <div class="col-md-4">
    
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Post", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>